from __future__ import annotations


from dataclasses import (
    asdict,
    dataclass,
)

from typing import (
    Any,
)


import pandas as pd


from app.discovery.schemas import (
    AnalysisDiscoveryReport,
    DiscoveredAnalysis,
)


# ============================================================
# VERSION
# ============================================================

FEATURE_LINEAGE_POLICY_VERSION = (
    "feature_lineage_policy_v0.1"
)


# ============================================================
# LINEAGE DESCRIPTOR
# ============================================================

@dataclass(
    frozen=True,
)
class FeatureLineage:
    column: str

    domain: str

    operation: str

    sources: tuple[
        str,
        ...,
    ]

    parents: tuple[
        str,
        ...,
    ] = ()

    summary_group: str | None = None

    identity_groups: tuple[
        str,
        ...,
    ] = ()

    scale_type: str = "unknown"

    generated: bool = True


# ============================================================
# DATASET HELPERS
# ============================================================

def build_dataset_map(
    datasets: list[
        dict[
            str,
            Any,
        ]
    ],
) -> dict[
    str,
    dict[
        str,
        Any,
    ],
]:
    return {
        str(
            dataset[
                "dataset_id"
            ]
        ):
            dataset

        for dataset
        in datasets
    }


def is_customer_behavior_dataset(
    dataset: dict[
        str,
        Any,
    ],
) -> bool:
    provenance = (
        dataset.get(
            "provenance",
            {},
        )
    )


    return (
        provenance.get(
            "operation"
        )
        ==
        "customer_behavior_materialization"
    )


# ============================================================
# FEATURE LINEAGE CONTRACT
# ============================================================

def build_customer_feature_lineage(
    dataset: dict[
        str,
        Any,
    ],
) -> dict[
    str,
    FeatureLineage,
]:
    """
    Build lineage for the standardized customer
    features generated by Analytical View Builder.

    These names are part of DataLens' own derived
    feature contract; they are not dataset-specific
    business-column hardcoding.
    """

    dataframe = dataset.get(
        "dataframe"
    )


    if not isinstance(
        dataframe,
        pd.DataFrame,
    ):
        return {}


    provenance = (
        dataset.get(
            "provenance",
            {},
        )
    )


    session_column = str(
        provenance.get(
            "source_session_column",
            "session_id",
        )
    )


    age_derivation = (
        provenance.get(
            "age_derivation"
        )
        or
        {}
    )


    birth_column = str(
        age_derivation.get(
            "birth_column",
            "birth",
        )
    )


    available = {
        str(
            column
        )

        for column
        in dataframe.columns
    }


    lineage: dict[
        str,
        FeatureLineage,
    ] = {}


    # ========================================================
    # TOTAL SPEND
    # ========================================================

    if (
        "total_spend"
        in available
    ):
        lineage[
            "total_spend"
        ] = FeatureLineage(
            column=
                "total_spend",

            domain=
                "behavior",

            operation=
                "sum",

            sources=(
                "basket_amount",
            ),

            identity_groups=(
                "basket_value_identity",
            ),

            scale_type=
                "extensive",
        )


    # ========================================================
    # PURCHASE SESSIONS
    # ========================================================

    if (
        "purchase_sessions"
        in available
    ):
        lineage[
            "purchase_sessions"
        ] = FeatureLineage(
            column=
                "purchase_sessions",

            domain=
                "behavior",

            operation=
                "nunique",

            sources=(
                session_column,
            ),

            identity_groups=(
                "basket_value_identity",
                "item_volume_identity",
            ),

            scale_type=
                "extensive",
        )


    # ========================================================
    # AVERAGE BASKET
    #
    # total_spend
    # -----------------
    # purchase_sessions
    # ========================================================

    if (
        "average_basket"
        in available
    ):
        lineage[
            "average_basket"
        ] = FeatureLineage(
            column=
                "average_basket",

            domain=
                "behavior",

            operation=
                "mean",

            sources=(
                "basket_amount",
            ),

            parents=(
                "total_spend",
                "purchase_sessions",
            ),

            summary_group=
                "basket_amount_summary",

            identity_groups=(
                "basket_value_identity",
            ),

            scale_type=
                "intensive",
        )


    # ========================================================
    # MEDIAN BASKET
    # ========================================================

    if (
        "median_basket"
        in available
    ):
        lineage[
            "median_basket"
        ] = FeatureLineage(
            column=
                "median_basket",

            domain=
                "behavior",

            operation=
                "median",

            sources=(
                "basket_amount",
            ),

            summary_group=
                "basket_amount_summary",

            scale_type=
                "intensive",
        )


    # ========================================================
    # TOTAL ITEMS
    # ========================================================

    if (
        "total_items"
        in available
    ):
        lineage[
            "total_items"
        ] = FeatureLineage(
            column=
                "total_items",

            domain=
                "behavior",

            operation=
                "sum",

            sources=(
                "item_count",
            ),

            identity_groups=(
                "item_volume_identity",
            ),

            scale_type=
                "extensive",
        )


    # ========================================================
    # AVERAGE ITEMS PER BASKET
    #
    # total_items
    # -----------------
    # purchase_sessions
    # ========================================================

    if (
        "average_items_per_basket"
        in available
    ):
        lineage[
            "average_items_per_basket"
        ] = FeatureLineage(
            column=
                "average_items_per_basket",

            domain=
                "behavior",

            operation=
                "mean",

            sources=(
                "item_count",
            ),

            parents=(
                "total_items",
                "purchase_sessions",
            ),

            summary_group=
                "item_count_summary",

            identity_groups=(
                "item_volume_identity",
            ),

            scale_type=
                "intensive",
        )


    # ========================================================
    # AGE AT FIRST PURCHASE
    # ========================================================

    if (
        "age_at_first_purchase"
        in available
    ):
        lineage[
            "age_at_first_purchase"
        ] = FeatureLineage(
            column=
                "age_at_first_purchase",

            domain=
                "demographic",

            operation=
                "difference",

            sources=(
                birth_column,
                "first_purchase",
            ),

            scale_type=
                "context",
        )


    return lineage


# ============================================================
# FALLBACK LINEAGE
# ============================================================

def fallback_lineage(
    column: str,
) -> FeatureLineage:
    """
    A column not generated by DataLens is treated
    conservatively as an external/context feature.

    This permits future customer attributes such as
    age, income, tenure, score, etc. to be compared
    with behavioural features without requiring
    hardcoded business-column names.
    """

    return FeatureLineage(
        column=
            column,

        domain=
            "context",

        operation=
            "observed",

        sources=(
            column,
        ),

        scale_type=
            "context",

        generated=
            False,
    )


# ============================================================
# CANDIDATE VARIABLE HELPERS
# ============================================================

def quantitative_candidate_columns(
    candidate: DiscoveredAnalysis,
) -> list[str]:
    result: list[
        str
    ] = []


    for variable in (
        candidate.variables
    ):
        if (
            variable.analysis_kind
            ==
            "quantitative"
            or
            variable.semantic_role
            in {
                "measure",
                "percentage",
            }
        ):
            if (
                variable.column
                not in result
            ):
                result.append(
                    variable.column
                )


    return result


# ============================================================
# LINEAGE RELATIONSHIP CLASSIFICATION
# ============================================================

def classify_lineage_relationship(
    left: FeatureLineage,
    right: FeatureLineage,
) -> dict[
    str,
    Any,
]:
    left_sources = set(
        left.sources
    )


    right_sources = set(
        right.sources
    )


    left_parents = set(
        left.parents
    )


    right_parents = set(
        right.parents
    )


    left_identities = set(
        left.identity_groups
    )


    right_identities = set(
        right.identity_groups
    )


    # ========================================================
    # 1. SAME DISTRIBUTION SUMMARY
    #
    # Example:
    # average_basket vs median_basket
    #
    # Both summarize exactly the same basket_amount
    # distribution for every customer.
    # ========================================================

    if (
        left.summary_group
        is not None
        and
        left.summary_group
        ==
        right.summary_group
        and
        {
            left.operation,
            right.operation,
        }
        <=
        {
            "mean",
            "median",
        }
    ):
        return {
            "relationship":
                "redundant_summary",

            "action":
                "suppress",

            "priority_adjustment":
                0.0,

            "reason":
                (
                    "Les deux variables résument "
                    "la même distribution source "
                    "avec des statistiques proches."
                ),
        }


    # ========================================================
    # 2. DIRECT FORMULA DEPENDENCY
    #
    # Example:
    # total_spend ↔ average_basket
    # purchase_sessions ↔ average_basket
    # ========================================================

    if (
        left.column
        in right_parents
        or
        right.column
        in left_parents
    ):
        return {
            "relationship":
                "formula_dependency",

            "action":
                "demote",

            "priority_adjustment":
                -45.0,

            "reason":
                (
                    "Une variable entre directement "
                    "dans la construction de l'autre."
                ),
        }


    # ========================================================
    # 3. SHARED ALGEBRAIC IDENTITY
    #
    # total_spend = average_basket
    #               × purchase_sessions
    #
    # total_items = average_items_per_basket
    #               × purchase_sessions
    # ========================================================

    common_identities = (
        left_identities
        &
        right_identities
    )


    if common_identities:
        if (
            left.scale_type
            ==
            "extensive"
            and
            right.scale_type
            ==
            "extensive"
        ):
            return {
                "relationship":
                    "shared_identity_extensive",

                "action":
                    "demote",

                "priority_adjustment":
                    -45.0,

                "reason":
                    (
                        "Les deux métriques appartiennent "
                        "à la même identité de construction "
                        "et augmentent avec l'activité "
                        "cumulée du client."
                    ),
            }


        return {
            "relationship":
                "shared_identity",

            "action":
                "demote",

            "priority_adjustment":
                -35.0,

            "reason":
                (
                    "Les deux métriques partagent une "
                    "identité de construction."
                ),
        }


    # ========================================================
    # 4. TWO EXTENSIVE BEHAVIOURAL METRICS
    #
    # Example:
    # total_spend ↔ total_items
    #
    # Both tend to increase simply because a customer
    # is more active over the observation window.
    # ========================================================

    if (
        left.domain
        ==
        "behavior"
        and
        right.domain
        ==
        "behavior"
        and
        left.scale_type
        ==
        "extensive"
        and
        right.scale_type
        ==
        "extensive"
    ):
        return {
            "relationship":
                "shared_activity_scale",

            "action":
                "demote",

            "priority_adjustment":
                -35.0,

            "reason":
                (
                    "Les deux métriques sont cumulatives "
                    "et peuvent être corrélées simplement "
                    "par le niveau global d'activité."
                ),
        }


    # ========================================================
    # 5. SAME SOURCE
    #
    # Example:
    # total_spend ↔ median_basket
    #
    # Not deterministic, but both originate from
    # basket_amount.
    # ========================================================

    if (
        left.domain
        ==
        "behavior"
        and
        right.domain
        ==
        "behavior"
        and
        left_sources
        &
        right_sources
    ):
        return {
            "relationship":
                "shared_source",

            "action":
                "demote",

            "priority_adjustment":
                -20.0,

            "reason":
                (
                    "Les deux métriques proviennent "
                    "d'une même mesure source."
                ),
        }


    # ========================================================
    # 6. CROSS-DOMAIN RELATIONSHIP
    #
    # Example:
    # demographic/context ↔ behavioural metric
    #
    # These are especially useful exploratory
    # relationships because one feature was not built
    # mechanically from the other.
    # ========================================================

    domains = {
        left.domain,
        right.domain,
    }


    if (
        "behavior"
        in domains
        and
        (
            "demographic"
            in domains
            or
            "context"
            in domains
        )
    ):
        return {
            "relationship":
                "cross_domain",

            "action":
                "promote",

            "priority_adjustment":
                15.0,

            "reason":
                (
                    "Les variables appartiennent à "
                    "des domaines de provenance "
                    "distincts : contexte/profil et "
                    "comportement."
                ),
        }


    # ========================================================
    # 7. INDEPENDENT / UNKNOWN
    # ========================================================

    return {
        "relationship":
            "independent_or_unknown",

        "action":
            "keep",

        "priority_adjustment":
            0.0,

        "reason":
            (
                "Aucune dépendance de construction "
                "directe n'a été détectée."
            ),
    }


# ============================================================
# DISCOVERY POLICY
# ============================================================

def apply_feature_lineage_policy(
    discovery: AnalysisDiscoveryReport,
    *,
    derived_datasets: list[
        dict[
            str,
            Any,
        ]
    ],
) -> AnalysisDiscoveryReport:
    """
    Inspect quantitative associations produced on
    DataLens customer-behaviour views.

    Important:
    - statistical execution remains deterministic;
    - lineage changes analytical priority, not the
      computed coefficient;
    - genuinely redundant summaries may be removed;
    - cross-domain relationships may be promoted.
    """

    dataset_map = (
        build_dataset_map(
            derived_datasets
        )
    )


    retained: list[
        DiscoveredAnalysis
    ] = []


    counters = {
        "suppressed":
            0,

        "demoted":
            0,

        "promoted":
            0,

        "kept":
            0,
    }


    for candidate in (
        discovery.candidates
    ):
        if (
            candidate.scope
            !=
            "single_dataset"
            or
            candidate.family
            !=
            "quantitative_association"
            or
            len(
                candidate.dataset_ids
            )
            !=
            1
        ):
            retained.append(
                candidate
            )

            continue


        dataset_id = str(
            candidate.dataset_ids[
                0
            ]
        )


        dataset = (
            dataset_map.get(
                dataset_id
            )
        )


        if (
            dataset is None
            or
            not is_customer_behavior_dataset(
                dataset
            )
        ):
            retained.append(
                candidate
            )

            continue


        columns = (
            quantitative_candidate_columns(
                candidate
            )
        )


        if (
            len(
                columns
            )
            !=
            2
        ):
            retained.append(
                candidate
            )

            continue


        lineage_map = (
            build_customer_feature_lineage(
                dataset
            )
        )


        left = (
            lineage_map.get(
                columns[
                    0
                ]
            )
            or
            fallback_lineage(
                columns[
                    0
                ]
            )
        )


        right = (
            lineage_map.get(
                columns[
                    1
                ]
            )
            or
            fallback_lineage(
                columns[
                    1
                ]
            )
        )


        classification = (
            classify_lineage_relationship(
                left,
                right,
            )
        )


        action = str(
            classification[
                "action"
            ]
        )


        candidate.observed_signals[
            "feature_lineage_policy"
        ] = {
            "version":
                FEATURE_LINEAGE_POLICY_VERSION,

            "left":
                asdict(
                    left
                ),

            "right":
                asdict(
                    right
                ),

            **classification,
        }


        if (
            action
            ==
            "suppress"
        ):
            counters[
                "suppressed"
            ] += 1

            continue


        adjustment = float(
            classification.get(
                "priority_adjustment",
                0.0,
            )
        )


        candidate.priority_score = round(
            max(
                0.0,
                min(
                    100.0,
                    candidate.priority_score
                    +
                    adjustment,
                ),
            ),
            2,
        )


        if (
            action
            ==
            "demote"
        ):
            counters[
                "demoted"
            ] += 1


            limitation = (
                "Priorité réduite par la politique "
                "de feature lineage : "
                +
                str(
                    classification[
                        "reason"
                    ]
                )
            )


            if (
                limitation
                not in candidate.limitations
            ):
                candidate.limitations.append(
                    limitation
                )


        elif (
            action
            ==
            "promote"
        ):
            counters[
                "promoted"
            ] += 1


            reason = (
                "Feature lineage : "
                +
                str(
                    classification[
                        "reason"
                    ]
                )
            )


            if (
                reason
                not in candidate.why_interesting
            ):
                candidate.why_interesting.append(
                    reason
                )


        else:
            counters[
                "kept"
            ] += 1


        retained.append(
            candidate
        )


    retained.sort(
        key=lambda candidate:
            candidate.priority_score,
        reverse=True,
    )


    discovery.candidates = (
        retained
    )


    discovery.candidate_count = (
        len(
            retained
        )
    )


    discovery.single_dataset_candidate_count = sum(
        1

        for candidate
        in retained

        if (
            candidate.scope
            ==
            "single_dataset"
        )
    )


    discovery.cross_dataset_candidate_count = sum(
        1

        for candidate
        in retained

        if (
            candidate.scope
            ==
            "cross_dataset"
        )
    )


    discovery.discovery_notes.extend(
        [
            (
                "Feature Lineage Policy "
                f"{FEATURE_LINEAGE_POLICY_VERSION} "
                "was applied."
            ),

            (
                f"{counters['suppressed']} "
                "redundant association(s) were "
                "suppressed."
            ),

            (
                f"{counters['demoted']} "
                "structurally related association(s) "
                "were demoted."
            ),

            (
                f"{counters['promoted']} "
                "cross-domain association(s) were "
                "promoted."
            ),
        ]
    )


    return discovery


# ============================================================
# RANKING POLICY
# ============================================================

def apply_feature_lineage_ranking_policy(
    ranking: Any,
    *,
    discovery: AnalysisDiscoveryReport,
) -> Any:
    """
    Apply tier constraints after the normal ranking.

    Discovery priority already contains the lineage
    penalty/bonus.

    This second stage prevents a mechanically strong
    coefficient from becoming a key business finding
    solely because two generated features share a
    construction path.
    """

    candidate_map = {
        candidate.analysis_id:
            candidate

        for candidate
        in discovery.candidates
    }


    structural_classes = {
        "formula_dependency",
        "shared_identity_extensive",
        "shared_identity",
        "shared_activity_scale",
        "shared_source",
    }


    hard_structural_classes = {
        "formula_dependency",
        "shared_identity_extensive",
        "shared_identity",
    }


    for finding in (
        ranking.findings
    ):
        candidate = (
            candidate_map.get(
                finding.analysis_id
            )
        )


        if candidate is None:
            continue


        policy = (
            candidate
            .observed_signals
            .get(
                "feature_lineage_policy"
            )
        )


        if not isinstance(
            policy,
            dict,
        ):
            continue


        relationship = str(
            policy.get(
                "relationship",
                "",
            )
        )


        # ====================================================
        # STRUCTURAL RELATION
        # ====================================================

        if (
            relationship
            in structural_classes
        ):
            reason = (
                "La relation est statistiquement "
                "mesurable mais sa priorité est "
                "réduite car les variables partagent "
                "une partie de leur construction."
            )


            if (
                reason
                not in finding.reasons
            ):
                finding.reasons.append(
                    reason
                )


            if (
                relationship
                in hard_structural_classes
            ):
                finding.interestingness_score = round(
                    min(
                        finding.interestingness_score,
                        54.0,
                    ),
                    2,
                )


                finding.tier = (
                    "supplementary"
                )


            else:
                finding.interestingness_score = round(
                    min(
                        finding.interestingness_score,
                        59.0,
                    ),
                    2,
                )


                if (
                    finding.signal_score
                    >=
                    60.0
                ):
                    finding.tier = (
                        "supporting_finding"
                    )

                else:
                    finding.tier = (
                        "supplementary"
                    )


        # ====================================================
        # CROSS-DOMAIN
        # ====================================================

        elif (
            relationship
            ==
            "cross_domain"
        ):
            finding.interestingness_score = round(
                min(
                    100.0,
                    finding.interestingness_score
                    +
                    8.0,
                ),
                2,
            )


            reason = (
                "La relation relie un attribut de "
                "profil ou de contexte à une métrique "
                "comportementale issue d'une autre "
                "branche de provenance."
            )


            if (
                reason
                not in finding.reasons
            ):
                finding.reasons.append(
                    reason
                )


            if (
                finding.signal_score
                >=
                60.0
                and
                finding.interestingness_score
                >=
                70.0
            ):
                finding.tier = (
                    "key_finding"
                )


    # ========================================================
    # RE-SORT
    # ========================================================

    tier_order = {
        "key_finding":
            3,

        "supporting_finding":
            2,

        "supplementary":
            1,

        "blocked":
            0,
    }


    ranking.findings.sort(
        key=lambda finding: (
            tier_order.get(
                finding.tier,
                0,
            ),

            finding.interestingness_score,
        ),
        reverse=True,
    )


    for index, finding in enumerate(
        ranking.findings,
        start=1,
    ):
        finding.rank = (
            index
        )


    ranking.ranked_count = (
        len(
            ranking.findings
        )
    )


    ranking.key_finding_count = sum(
        1

        for finding
        in ranking.findings

        if (
            finding.tier
            ==
            "key_finding"
        )
    )


    ranking.supporting_finding_count = sum(
        1

        for finding
        in ranking.findings

        if (
            finding.tier
            ==
            "supporting_finding"
        )
    )


    ranking.supplementary_count = sum(
        1

        for finding
        in ranking.findings

        if (
            finding.tier
            ==
            "supplementary"
        )
    )


    ranking.blocked_count = sum(
        1

        for finding
        in ranking.findings

        if (
            finding.tier
            ==
            "blocked"
        )
    )


    ranking.ranking_notes.append(
        (
            "Feature lineage is used to distinguish "
            "strong business signals from "
            "associations partly created by "
            "DataLens feature engineering."
        )
    )


    return ranking
